apiVersion: v1
kind: Pod
metadata:
  name: nginx-x86
spec:
  nodeSelector:
    karpenter.sh/capacity-type: on-demand
    kubernetes.io/arch: amd64
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"